### ISSUE TITLE
This driver not working with kernel 4.4

### ISSUE THREAD

**Issue by tcheunch** [jsln/pps-gen-gpio#1]
Hi Jsolano, 

I am trying to use your driver with the Linux Kernel version 4.4, but it gives the following error: 

drivers/pps/generators/pps_gen_gpio.c: In function ‘pps_gen_gpio_probe’:
drivers/pps/generators/pps_gen_gpio.c:201:22: error: too few arguments to function ‘devm_gpiod_get’
  devdata->pps_gpio = devm_gpiod_get(dev, "pps-gen");
                      ^
In file included from include/asm-generic/gpio.h:13:0,
                 from ./arch/arm/include/asm/gpio.h:9,
                 from include/linux/gpio.h:48,
                 from drivers/pps/generators/pps_gen_gpio.c:32:
include/linux/gpio/consumer.h:73:32: note: declared here
 struct gpio_desc *__must_check devm_gpiod_get(struct device *dev,

I am expecting that the new kernel calls devm_gpiod_get differently. Is it possible that that is the case? 

Thanks in advance.

**Comment by jsln** [comment]
Hi,
the devm_gpiod_get function has changed as you say, this driver needs to be updated for recent kernels.

In the meantime, can you try adding a 0 as third argument to that function?
Juan.

**Comment by gizero** [comment]
Hi! Just landed on this project while looking for something to generate PPS from a Linux system. I'm going to give it a try and I'm wondering if you ever thought about upstreaming it: a quick search revealed no evidence of submission on LKML. It may be a tedious process, but, as soon as completed, it's going to grant the best for-free maintenance against i.e. breakages due to kernel API changes.

**Comment by Mani-Sadhasivam** [comment]
any thought on upstreaming this?

**Comment by gizero** [comment]
@Mani-Sadhasivam not from the original author as far as I can see... I'll have to get back to building this for another kernel and I'll take the time to think about the effort for upstreaming. My main concern when I first looked at it was about the high level of code duplication from the parallel port PPS generator this is derived from. To make this reasonably suitable for upstreaming at least some sort of code factorisation will be needed IMHO.

**Comment by gizero** [comment]
...also [here](https://groups.google.com/forum/#!topic/fa.linux.kernel/4iFqiQ3u_LE) is a reason why the whole approach taken from the parport PPS generator driver was flagged as broken. Don't think posting this one with the current implementation can go any further... Moreover, this is so since 2011: seems like no one has ever looked into fixing it since then.

**Comment by Mani-Sadhasivam** [comment]
@gizero You are right! Also, TBH the whole PPS subsystem in linux kernel seems to be fragmented and it needs someone to fix that too. Regarding this driver, I'll also give it a shot in dragonboard and see what sort of commitment I can give for upstreaming.

**Comment by jsln** [comment]
@gizero @Mani-Sadhasivam  Guys, I am afraid I don't have much time currently to follow up on this. As far as I remember, upstreaming was frowned upon by some kernel maintainers due to the disabling of interrupts and the busy loop.

**Comment by jsln** [comment]
Hi guys,

I finally got some time to fix this driver. I have tested it with kernel 4.14.20.

Regarding upstreaming, I guess the only way to have a chance is to remove the busy waits, which will make the PPS timing less precise in systems with significant interrupt-related CPU load.

Regards,
Juan.
